package extjson

import (
	"bytes"
	"fmt"
	"strings"

	jen "github.com/dave/jennifer/jen"
	//"github.com/sindbach/json-to-bson-go/jsonutil"
	"go.mongodb.org/mongo-driver/bson/bsonrw"
	"go.mongodb.org/mongo-driver/bson/bsontype"
)

func Convert(jsonStr []byte, canonical bool) (string, error) {
	ejvr, err := bsonrw.NewExtJSONValueReader(bytes.NewReader(jsonStr), canonical)
	if err != nil {
		return "", err
	}
	if ejvr.Type() != bsontype.EmbeddedDocument {
		return "", fmt.Errorf("expected document type, got %s", ejvr.Type())
	}

	docReader, err := ejvr.ReadDocument()
	if err != nil {
		return "", err
	}

	var fields []jen.Code
	key, ejvr, err := docReader.ReadElement()
	for err == nil {
		elem := jen.Id(strings.Title(key))
		structTags := []string{key}

		switch ejvr.Type() {
		case bsontype.Double:
			elem.Add(jen.Float64())
		case bsontype.String:
			elem.Add(jen.String())
		case bsontype.Boolean:
			elem.Add(jen.Bool())
		case bsontype.Int32:
			elem.Add(jen.Int32())
		case bsontype.Int64:
			elem.Add(jen.Int64())
		case bsontype.Binary:
			elem.Add(jen.Qual("primitive", "Binary"))
		case bsontype.Undefined:
			elem.Add(jen.Qual("primitive", "Undefined"))
		case bsontype.ObjectID:
			elem.Add(jen.Qual("primitive", "ObjectID"))
		case bsontype.DateTime:
			elem.Add(jen.Qual("primitive", "DateTime"))
		case bsontype.Null: // TODO: maybe should be interface{}
			elem.Add(jen.Qual("primitive", "Null"))
		case bsontype.Regex:
			elem.Add(jen.Qual("primitive", "Regex"))
		case bsontype.DBPointer:
			elem.Add(jen.Qual("primitive", "DBPointer"))
		case bsontype.JavaScript:
			elem.Add(jen.Qual("primitive", "JavaScript"))
		case bsontype.Symbol:
			elem.Add(jen.Qual("primitive", "Symbol"))
		case bsontype.CodeWithScope:
			elem.Add(jen.Qual("primitive", "CodeWithScope"))
		case bsontype.Timestamp:
			elem.Add(jen.Qual("primitive", "Timestamp"))
		case bsontype.Decimal128:
			elem.Add(jen.Qual("primitive", "Decimal128"))
		case bsontype.MinKey:
			elem.Add(jen.Qual("primitive", "MinKey"))
		case bsontype.MaxKey:
			elem.Add(jen.Qual("primitive", "MaxKey"))
		//TODO: embedded doc, Array
		default:
			return "", fmt.Errorf("Unknown type: %s", ejvr.Type())
		}

		tagsString := strings.Join(structTags, ",")
		elem.Tag(map[string]string{"bson": tagsString})
		fields = append(fields, elem)
		err = ejvr.Skip()
		if err != nil {
			return "", err
		}
		key, ejvr, err = docReader.ReadElement()
	}

	output := jen.NewFile("main")
	output.Type().Id("AutoGenerated").Struct(fields...)
	return output.GoString(), nil
}
